/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opencv_samples_imagemanipulations_ImageManipulationsActivity */

#ifndef _Included_org_opencv_samples_imagemanipulations_ImageManipulationsActivity
#define _Included_org_opencv_samples_imagemanipulations_ImageManipulationsActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opencv_samples_imagemanipulations_ImageManipulationsActivity
 * Method:    computeLineHeight
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_opencv_samples_imagemanipulations_ImageManipulationsActivity_computeLineHeight
        (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     org_opencv_samples_imagemanipulations_ImageManipulationsActivity
 * Method:    colorizeLine
 * Signature: (JIII)I
 */
JNIEXPORT jint JNICALL Java_org_opencv_samples_imagemanipulations_ImageManipulationsActivity_colorizeLine
        (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
